"""fix_clarification_turns_type

Revision ID: d14572b7190f
Revises: d33cabdd1d3d
Create Date: 2026-09-06 08:11:55.871474
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd14572b7190f'
down_revision: Union[str, None] = 'd33cabdd1d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'conversations', 'clarification_turns',
        existing_type=sa.VARCHAR(length=8),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="clarification_turns::integer",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'clarification_turns',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
