"""make_sequence_number_nullable

Revision ID: d33cabdd1d3d
Revises: 02940cb324e6
Create Date: 2026-09-06 08:06:51.005361
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd33cabdd1d3d'
down_revision: Union[str, None] = '02940cb324e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'sequence_number',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('audit_logs_sequence_number_key', 'audit_logs', type_='unique')
    op.create_foreign_key(None, 'conversations', 'incidents', ['incident_id'], ['id'], use_alter=True)
    op.alter_column('event_outbox', 'sequence_number',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('event_outbox_sequence_number_key', 'event_outbox', type_='unique')
    op.create_foreign_key(None, 'incidents', 'conversations', ['reporter_conversation_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.create_unique_constraint('event_outbox_sequence_number_key', 'event_outbox', ['sequence_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('event_outbox', 'sequence_number',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_unique_constraint('audit_logs_sequence_number_key', 'audit_logs', ['sequence_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('audit_logs', 'sequence_number',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
